project_id = "vigdgbydpumkauibuxmn"

[functions.collect-revenue]
verify_jwt = false

[functions.daily-profits]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.sendavapay-webhook]
verify_jwt = false

[functions.omnipay-webhook]
verify_jwt = false